---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "temporal"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: postgres
spec:
    type: NodePort
    selector:
      app: postgres
    ports:
    - nodePort: 31234
      port: 5432
      targetPort: 5432